THE GREAT COMPILER TUTORIAL
        by 'Uladox

 c(){//    "THE
    int     COMPILER
     c;
     /**/     HELLO
       c=4;     WORLD
      return c;
       nil\* *\}   !
    '( )     .text   ";
   'sch        asm:
 'lambda        movl $42, 
(+ x x)           %eax

* Why? Just why?
  - There are few and far between
    compiler tutorials and the few
    out there are outdated or are
    not fun. Simple as that.
* What languages
** Output
   - The output of the compiler
     with be gas assembly with
     a c based standard library.
     Good programmers should have
     some grasp of assembly plus if
     you can target it for nontrivial
     matter you can target higher things.
** Compiler
   - The compiler's language will change
     based off of part of the tutorial
     starting off in ruby and moving into
     red and into other languages before
     ending with c.
** Source
   - The source will most of the
     subset of the interesting part
     of the scheme programming language.
